---
name: "Assign issue and label"

on:
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.0
        with:
          title-or-body: both
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parameters: '[{"keywords": ["bug", "broken"], "labels": ["bug"]}]'
